In [1]:
import numpy as np

In [6]:
arr = np.arange(0, 21, 1)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [7]:
nb = 10

In [11]:
freqs, bins = np.histogram(arr, nb)

In [12]:
bins

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [13]:
freqs

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 3], dtype=int64)

In [17]:
bins_cent = 0.5 * (bins[1:] + bins[:-1])
bins_cent

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19.])

In [18]:
len(bins_cent)

10

In [19]:
len(freqs)

10